name: vanna
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.2
  - aiosignal=1.4.0
  - annotated-types=0.7.0
  - anyio=4.11.0
  - asttokens=3.0.0
  - async-timeout=4.0.3
  - attrs=25.4.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - comm=0.2.3
  - debugpy=1.8.17
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - greenlet=3.2.4
  - h11=0.16.0
  - h2=4.3.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - idna=3.11
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipython=9.6.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - keyutils=1.6.3
  - krb5=1.21.3
  - langchain=1.0.3
  - langchain-core=1.0.3
  - langchain-text-splitters=0.3.11
  - langgraph=1.0.2
  - langgraph-checkpoint=3.0.0
  - langgraph-prebuilt=1.0.2
  - langgraph-sdk=0.2.9
  - ld_impl_linux-64=2.44
  - libblas=3.9.0
  - libcblas=3.9.0
  - libedit=3.1.20250104
  - libexpat=2.7.1
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.41.2
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - matplotlib-inline=0.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy=2.3.4
  - openssl=3.5.4
  - orjson=3.11.4
  - ormsgpack=1.11.0
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.2
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.2
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pydantic=2.12.3
  - pydantic-core=2.41.4
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-xxhash=3.6.0
  - python_abi=3.11
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - readline=8.2
  - requests=2.32.5
  - requests-toolbelt=1.0.0
  - setuptools=80.9.0
  - six=1.17.0
  - sniffio=1.3.1
  - sqlalchemy=2.0.44
  - stack_data=0.6.3
  - tenacity=9.1.2
  - tk=8.6.13
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xxhash=0.8.3
  - yaml=0.2.5
  - yarl=1.22.0
  - zeromq=4.3.5
  - zipp=3.23.0
  - zstd=1.5.7
  - pip:
      - annotated-doc==0.0.3
      - asgiref==3.10.0
      - backoff==2.2.1
      - bcrypt==5.0.0
      - blinker==1.9.0
      - build==1.3.0
      - cachetools==6.2.1
      - choreographer==1.2.0
      - chroma-hnswlib==0.7.6
      - chromadb==0.6.3
      - click==8.3.0
      - clickhouse-connect==0.9.2
      - coloredlogs==15.0.1
      - cryptography==46.0.3
      - dashscope==1.24.9
      - distro==1.9.0
      - duckdb==1.4.1
      - durationpy==0.10
      - environs==9.5.0
      - fastapi==0.120.3
      - filelock==3.20.0
      - flasgger==0.9.7.1
      - flask==3.1.2
      - flask-sock==0.7.0
      - flatbuffers==25.9.23
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - future==1.0.0
      - google-api-core==2.28.1
      - google-auth==2.42.1
      - google-cloud-bigquery==3.38.0
      - google-cloud-core==2.5.0
      - google-crc32c==1.7.1
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.71.0
      - grpcio==1.76.0
      - grpcio-status==1.76.0
      - hf-xet==1.2.0
      - httptools==0.7.1
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - importlib-resources==6.5.2
      - iniconfig==2.3.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jiter==0.11.1
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kaleido==1.1.0
      - kubernetes==34.1.0
      - langchain-openai==1.0.2
      - langsmith==0.4.40
      - logistro==2.0.0
      - lz4==4.4.5
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - marshmallow==3.26.1
      - mdurl==0.1.2
      - milvus-lite==2.4.12
      - milvus-model==0.2.12
      - mistune==3.1.4
      - mmh3==5.2.0
      - monotonic==1.6
      - mpmath==1.3.0
      - multidict==6.7.0
      - narwhals==2.10.0
      - oauthlib==3.3.1
      - onnxruntime==1.23.2
      - openai==2.6.1
      - opentelemetry-api==1.37.0
      - opentelemetry-exporter-otlp-proto-common==1.37.0
      - opentelemetry-exporter-otlp-proto-grpc==1.37.0
      - opentelemetry-instrumentation==0.58b0
      - opentelemetry-instrumentation-asgi==0.58b0
      - opentelemetry-instrumentation-fastapi==0.58b0
      - opentelemetry-proto==1.37.0
      - opentelemetry-sdk==1.37.0
      - opentelemetry-semantic-conventions==0.58b0
      - opentelemetry-util-http==0.58b0
      - oracledb==3.4.0
      - overrides==7.7.0
      - pandas==2.3.3
      - plotly==6.3.1
      - pluggy==1.6.0
      - posthog==2.4.2
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==6.33.0
      - psycopg2-binary==2.9.11
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.2
      - pycparser==2.23
      - pyhive==0.7.0
      - pymilvus==2.4.9
      - pymilvus-model==0.3.2
      - pymysql==1.1.2
      - pyodbc==5.3.0
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - pytest==8.4.2
      - pytest-timeout==2.4.0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - referencing==0.37.0
      - regex==2025.10.23
      - requests-oauthlib==2.0.0
      - rich==14.2.0
      - rpds-py==0.28.0
      - rsa==4.9.1
      - safetensors==0.6.2
      - scipy==1.16.3
      - shellingham==1.5.4
      - simple-websocket==1.1.0
      - simplejson==3.20.2
      - sqlparse==0.5.3
      - starlette==0.49.1
      - sympy==1.14.0
      - tabulate==0.9.0
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - tqdm==4.67.1
      - transformers==4.57.1
      - typer==0.20.0
      - typer-slim==0.20.0
      - tzdata==2025.2
      - ujson==5.11.0
      - urllib3==2.3.0
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - vanna==0.7.9
      - watchfiles==1.1.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==1.17.3
      - wsproto==1.2.0
      - zstandard==0.25.0
prefix: /home/data/nongwa/miniconda3/envs/vanna
